### ISSUE TITLE
CMake example doesn't work

### ISSUE THREAD

**Issue by Learath2** [wasmerio/wasmer-c-api#6]
`ExternalProject_Add` creates a target which builds at build time, `find_library` happens at configure time, I don't see how it's supposed to ever work to begin with.

**Comment by torch2424** [comment]
Perhaps @MarkMcCaskey @nlewycky can help? 🤔 😄

**Comment by MarkMcCaskey** [comment]
Will Investigate -- I wasn't getting notifications from this repo!

**Comment by MarkMcCaskey** [comment]
Okay!  Thanks for reporting this!  This should be fixed in 90e3821a1a983cf82af5587788d577f15bba0b61 .  There might be a better way to check for errors here.  Please let us know if you run into any other issues or have ideas to improve things!

**Comment by Type1J** [comment]
I believe that there's a way to specify that a library in a list of libraries is for "debug" or "optimized" (release) builds. The cargo build command needs to be run twice: once as it is, and once with `--release`, then both libraries need to be in the CMake var with the library paths, but they should be prefixed with "debug" and "optimized". I may make a PR for that soon, but you're likely to beat me to it.

**Comment by MarkMcCaskey** [comment]
@Type1J that would be very useful!  I'd love it if you could make a PR doing that -- I don't really know CMake that well and it always takes me far longer than it should to get things working. 😄
