### ISSUE TITLE
Compilation of an example without cmake

### ISSUE THREAD

**Issue by alocquet** [wasmerio/wasmer-c-api#8]
Hello,
Is it necessary to download 'libwasmer_runtime_c_api.so' (https://github.com/wasmerio/wasmer/releases/download/0.8.0/libwasmer_runtime_c_api.so) to build a C file which call wasmer_runtime api ? 
I have spend some time to find it (I have even recompiled it before I have found it). I think it should be a good thing to explain it in documentation. I can do a PR if you want :)

**Comment by torch2424** [comment]
cc @MarkMcCaskey , @nlewycky , @Hywan  Can you help out with this? 😄

**Comment by alocquet** [comment]
I think this issue is useless ans should be closed. The origin of our problem was to find 'so' lib when we were compiling https://github.com/wasmerio/wasmer/blob/master/lib/runtime-c-api/README.md example.
The link to release page has been added in this example.

**Comment by torch2424** [comment]
@alocquet Oh nice! I'm glad you figured it out! As you suggested, I'll go ahead and close this. Feel free to re-open, or open a new issue if anything else pops up! 😄 👍
